version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0 # Use a specific version
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false # For development, disable security
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elk-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0 # Use the same version as Elasticsearch
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elk-network

  broker:
      image: apache/kafka:latest
      container_name: broker
      environment:
        KAFKA_NODE_ID: 1
        KAFKA_PROCESS_ROLES: broker,controller
        KAFKA_LISTENERS: PLAINTEXT://broker:9092,CONTROLLER://broker:9093
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
        KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
        KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        KAFKA_NUM_PARTITIONS: 3
      ports:
        - "9092:9092"
      networks:
        - elk-network

  retriever:
    image: retriever:latest
    container_name: retriever
    environment:
      MONGO_HOST: "mongodb"
      ELASTIC_HOST: "http://elasticsearch:"
      KAFKA_HOST: "broker"

    ports:
      - "10000:10000"
    networks:
      - elk-network
    volumes:
      - esdata:/data


  export:
    image: export:latest
    container_name: export
    environment:
      MONGO_HOST: "mongodb"
      ELASTIC_HOST: "http://elasticsearch:"
      KAFKA_HOST: "broker"

    ports:
      - "10000:10000"
    networks:
      - elk-network
    volumes:
      - esdata:/data


volumes:
  esdata:
    driver: local

networks:
  elk-network:
    driver: bridge